<?php
error_reporting(E_ALL);
ini_set('display_errors',TRUE);
ini_set('display_startup_errors',TRUE);
function spatula_help($path, $args)
{
 switch ($path) {
    case "admin/help#spatula":
      return '<p>' . t("Adds fitness pets to the system") . '</p>';
      break;
  }
}
function spatula_theme() {
	return array(
		'spatula_sidebar' => array(
			'variables' => array(
					'username' => NULL,
					'imgurl' => NULL,
					'typename' => NULL,
					'petname' => NULL,
					'exp' => NULL,
					'happiness' => NULL
				)
				),
		'spatula_main' => array(
			'variables' => array(
				'data' => array(
					'username' => NULL,
					'imgurl' => NULL,
					'typename' => NULL,
					'petname' => NULL,
					'exp' => NULL,
					'happiness' => NULL
					)
				)
			)
			);
			
}
function theme_spatula_sidebar($data) {
/*$data should always contain:
$username
$imgurl
$petname
$exp
$happiness
*/
$path = "http://bmyf.clanslots.com/drupal/includes/images/bigthumb/";
$output = "<center><div id = 'sidebar' class = 'sidebar'><div id = 'sidebar_username' class = 'text'>".$data['username']."</div>";
$output .= "<div id = 'sidebar_image' class = 'image'><img src = '".$path.$data['imgurl']."' alt='Pet Image' /></div>";
$output .= "<div id = 'sidebar_name' class = 'text'>".$data['petname']." - Level ".exp_to_level($data['exp'])."</div>";
$output .= "<div id = 'sidebar_stats' class = 'smalltext'><div id = 'species'>".$data['typename']."</div><div id = 'experience'>Experience: ";
$output .= $data['exp']."</div><div id = 'happiness'>Happiness: ".$data['happiness']."</div></div></div></center>";
return $output;

}
function spatula_menu() {
  $items['spatula'] = array(
    'title' => 'My Pet Page',
    'page callback' => 'spatula_block_view',
	'page arguments' => 'spatulamain',
	'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
function theme_spatula_main($data) {
$row = $data->fetchAssoc();

$path = "http://bmyf.clanslots.com/drupal/includes/images/bigthumb/";
$output = "<center><div id = 'sidebar' class = 'sidebar'><div id = 'main_username' class = 'text'>".$row['username']."</div>";
$output .= "<div id = 'sidebar_image' class = 'image'><img src = '".$path.$row['imgurl']."' alt='Pet Image' /></div>";
$output .= "<div id = 'sidebar_name' class = 'text'>".$row['petname']." - Level ".exp_to_level($row['exp'])."</div>";
$output .= "<div id = 'sidebar_stats' class = 'smalltext'><div id = 'species'>".$row['typename']."</div><div id = 'experience'>Experience: ";
$output .= $row['exp']."</div><div id = 'happiness'>Happiness: ".$row['happiness']."</div></div></div></center>";

$path = "http://bmyf.clanslots.com/drupal/includes/images/smallthumb/";
$output .= "<table id= 'otherpets' class = 'main'><tr>";
foreach($data as $row)
{
$output .= "<td><div id = 'main_username' class = 'text'>".$row['username']."</div>";
$output .= "<div id = 'main_image' class = 'image'><img src = '".$path.$row['imgurl']."' alt='Pet Image' /></div>";
$output .= "<div id = 'main_name' class = 'text'>".$row['petname']." - Level ".exp_to_level($row['exp'])."</div>";
$output .= "<div id = 'main_stats' class = 'smalltext'><div id = 'species'>".$row['typename']."</div><div id = 'experience'>Experience: ";
$output .= $row['exp']."</div><div id = 'happiness'>Happiness: ".$row['happiness']."</div></div></td>";
}
$output .= "</tr></table>";
return $output;
}
function exp_to_level($experience)
{
$level_list = array( 
				'1' => 0,
				'2' => 10,
				'3' => 20,
				'4' => 40,
				'5' => 100,
				'6' => 220,
				'7' => 450,
				'8' => 900,
				'9' => 2100,
				'10' => 5000);
foreach($level_list as $level => $levelexp)
	if ($levelexp <= $experience)
		$curlev =$level;
	else return $curlev;
	
}

function spatula_block_info() {
  $blocks['spatula'] = array(
    // The name that will appear in the block list.
    'info' => t('Active Pet'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE);
  $blocks['spatulamain'] = array(
  'info' => t('Pet Information'),
  'cache' => DRUPAL_CACHE_PER_ROLE);
  return $blocks;
  }
 function spatula_pet($arg = "primary"){
global $user;
if ($arg == "primary")
$pets = db_query("SELECT p.id, p.uid, p.name, p.exp, p.happiness, p.type FROM {pet} p WHERE uid = :uid AND `primary` = :primary", array(':uid' => $user->uid, ':primary' => 1));	
else if ($arg == "all")
$pets = db_query("SELECT p.id, p.uid, p.name, p.exp, p.happiness, p.type FROM {pet} p WHERE uid = :uid", array(':uid' => $user->uid));	
else
$pets = db_query("SELECT p.id, p.uid, p.name, p.exp, p.happiness, p.type FROM {pet} p WHERE id = :id", array(':id' => $arg));
return $pets;
			}
function spatula_image($id = NULL){
$pets = spatula_pet($id)->fetchAssoc();

$types = db_select('pet_types','pt')
		-> fields('pt', array('type','typename','imgurl'))
		-> condition('type', $pets['type'])
		-> execute();
		return $types->fetchAssoc();
		}
function spatula_block_view($type = '') 
{
	global $user;
	
	$show = variable_get('spatula_show', 1);
	switch ($type) 
	{
	
		case 'spatula':
		
			$block['subject'] = t('Pet Information');
			if (user_access('access content')) {
				$query = spatula_pet();
				$pet = $query -> fetchAssoc();
				$petimage = spatula_image($pet['id']);
				$data = array('username' => $user->name, 
						'imgurl' => $petimage['imgurl'], 
						'typename' => $petimage['typename'],
						'petname' => $pet['name'], 
						'exp' => $pet['exp'], 
						'happiness' => $pet['happiness']
						);
						
				if (empty($data)) 
				{
					$block['content'] = t('No primary pet set');
				}
				else 
				{
					$block['content'] =  theme('spatula_sidebar', $data);
					return $block;
				}
			}
			
		case 'spatulamain':
			$block['subject'] = t('All Pet Information');
			if (user_access('access content')) 
			{
			
				$primpet = spatula_pet()->fetchAssoc();
				$pets = spatula_pet("all");
				$petimage = spatula_image($primpet['id']);
				$petlist = array();
				$petlist[] = array('username' => $user->name, 'imgurl' => $petimage['imgurl'], 'petname' => $primpet['name'], 'exp' => $primpet['exp'], 'happiness' =>$primpet['happiness']);
				
				foreach($pets as $pet)
				{
				
				$petimage = spatula_image($pet->id);
					if ($primpet['id'] != $pet->id)
					$petlist[] = array('username' => $user->name, 'imgurl' => $petimage['imgurl'], 'petname' => $pet->name, 'exp' => $pet->exp, 'happiness' =>$pet->happiness);
				}
				if (empty($petlist))
					$block['content'] = t('No pets exist');
				else
				{
					$block['content'] = theme('spatula_main', array('data' => $petlist));
				}
				return $block;
			}
			
	}
}